sudo: false

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@latest
  - npm i -g cross-env sass-lint standard eslint-plugin-flowtype babel-eslint snazzy
  - npm install

script:
  - npm run test
